# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcDIz4ITskdRf5vajwibx5Zn9OX6_v4h
"""

a = 0
i = 0
while a < 100:
  a+=1
  if a%2==0:
    i+=1
    print(a)
print(i)